In [2]:
import duckdb

from azdata.paths import RAW_DIR

In [3]:
# General information: data range, null counts
# Worldbank

result = duckdb.sql(f"""
    SELECT
        MIN(year) as first_year,
        MAX(year) as last_year,
        COUNT(*) FILTER (WHERE gdp IS NULL) as gdp_nulls,
        COUNT(*) FILTER (WHERE inflation IS NULL) as inflation_nulls,
    FROM '{RAW_DIR / "worldbank.csv"}'
""").df()

result

   first_year  last_year  gdp_nulls  inflation_nulls
0        1960       2025         31               33

In [5]:
# Fred

result = duckdb.sql(f"""
    SELECT
        MIN(year) as first_year,
        MAX(year) as last_year,
        COUNT(*) FILTER (WHERE oil_price IS NULL) as oil_price_nulls,
    FROM '{RAW_DIR / "fred.csv"}'
""").df()

result

  first_year  last_year  oil_price_nulls
0 1987-01-01 2026-01-01                2

In [ ]:
# Years with high inflation rate

result = duckdb.sql(f"""
    SELECT
        year,
        inflation,
    FROM '{RAW_DIR / "worldbank.csv"}'
    WHERE inflation > 10
""").df()

result

   year    inflation
0  1993  1128.000024
1  1994  1662.215949
2  1995   411.759642
3  1996    19.794803
4  2007    16.699755
5  2008    20.849087
6  2016    12.443375
7  2017    12.935918
8  2022    13.852259

In [ ]:
# Oil price categories

result = duckdb.sql(f"""
    SELECT
        year,
        CASE
            WHEN oil_price > 80 THEN 'High'
            WHEN oil_price BETWEEN 40 and 80 THEN 'Medium'
            WHEN oil_price < 40 THEN 'Low'
        END AS oil_price_category
    FROM '{RAW_DIR / "fred.csv"}'
""").df()

result

         year oil_price_category
0  1987-01-01                NaN
1  1988-01-01                Low
2  1989-01-01                Low
3  1990-01-01                Low
4  1991-01-01                Low
5  1992-01-01                Low
6  1993-01-01                Low
7  1994-01-01                Low
8  1995-01-01                Low
9  1996-01-01                Low
10 1997-01-01                Low
11 1998-01-01                Low
12 1999-01-01                Low
13 2000-01-01                Low
14 2001-01-01                Low
15 2002-01-01                Low
16 2003-01-01                Low
17 2004-01-01                Low
18 2005-01-01             Medium
19 2006-01-01             Medium
20 2007-01-01             Medium
21 2008-01-01               High
22 2009-01-01             Medium
23 2010-01-01             Medium
24 2011-01-01               High
25 2012-01-01               High
26 2013-01-01               High
27 2014-01-01               High
28 2015-01-01             Medium
29 2016-01-01             Medium
30 2017-01-01             Medium
31 2018-01-01             Medium
32 2019-01-01             Medium
33 2020-01-01             Medium
34 2021-01-01             Medium
35 2022-01-01               High
36 2023-01-01               High
37 2024-01-01               High
38 2025-01-01             Medium
39 2026-01-01                NaN

In [34]:
result = duckdb.sql(f"""
    SELECT *
    FROM '{RAW_DIR / "fred.csv"}' f
    INNER JOIN '{RAW_DIR / "worldbank.csv"}' w
        ON EXTRACT(YEAR FROM f.year)::INTEGER = w.year
""").df()

result

,year,oil_price,year_1,gdp,unemployment_rate,exports_pct_gdp,gdp_growth,inflation,current_account,imports_pct_gdp
0,1987-01-01,NaN,1987,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1988-01-01,14.91,1988,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1989-01-01,18.23,1989,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1990-01-01,23.76,1990,8.884848e+09,NaN,43.860846,NaN,NaN,NaN,39.222374
4,1991-01-01,20.04,1991,5.344000e+09,0.900,45.658683,-0.700000,NaN,NaN,41.205090
5,1992-01-01,19.32,1992,4.446587e+08,1.800,86.203606,-22.600000,-10.630097,NaN,54.596378
6,1993-01-01,17.01,1993,1.570393e+09,4.500,57.462420,-23.099999,1128.000024,NaN,76.028025
7,1994-01-01,15.86,1994,1.193141e+09,6.300,24.721110,-19.700001,1662.215949,NaN,30.628209
8,1995-01-01,17.02,1995,2.417331e+09,7.200,32.486644,-11.799999,411.759642,-4.006500e+08,53.407067
9,1996-01-01,20.64,1996,3.176507e+09,8.100,24.928639,1.299999,19.794803,-9.311820e+08,55.921101
10,1997-01-01,19.11,1997,3.962362e+09,9.100,29.034607,5.800000,3.674348,-9.157550e+08,53.044359
11,1998-01-01,12.76,1998,4.446369e+09,10.000,22.699529,10.000000,-0.772698,-1.364521e+09,54.528280
12,1999-01-01,17.90,1999,4.581249e+09,10.900,27.970120,7.400001,-8.525170,-5.997030e+08,41.855845
13,2000-01-01,28.66,2000,5.272616e+09,11.780,40.170831,11.099999,1.805003,-1.677730e+08,38.377737
14,2001-01-01,24.46,2001,5.707616e+09,10.910,41.498608,9.900000,1.547196,-5.175500e+07,37.316578
15,2002-01-01,24.99,2002,6.236088e+09,10.040,42.767835,9.438916,2.771165,-7.683730e+08,50.050309
16,2003-01-01,28.85,2003,7.276413e+09,9.170,42.006577,10.208299,2.233865,-2.020854e+09,65.545372
17,2004-01-01,38.26,2004,8.680406e+09,7.990,48.789008,9.253802,6.708930,-2.589213e+09,72.718107
18,2005-01-01,54.57,2005,1.324542e+10,7.260,62.941106,27.961538,9.679507,1.673150e+08,52.900779
19,2006-01-01,65.16,2006,2.098193e+10,6.620,66.504145,34.466210,8.328925,3.707605e+09,38.758255
20,2007-01-01,72.44,2007,3.304942e+10,6.330,68.128912,25.463216,16.699755,9.018885e+09,28.512896
21,2008-01-01,96.94,2008,4.885129e+10,5.860,65.776138,10.591437,20.849087,1.645280e+10,23.466759
22,2009-01-01,61.74,2009,4.429243e+10,5.740,51.635746,9.369503,1.457048,1.017488e+10,23.108296
23,2010-01-01,79.61,2010,5.290929e+10,5.630,54.304722,4.788832,5.726872,1.504044e+10,20.681267
24,2011-01-01,111.26,2011,6.595280e+10,5.420,56.426981,-1.572997,7.858333,1.714494e+10,24.081064
25,2012-01-01,111.57,2012,6.967994e+10,5.190,52.974680,2.202939,1.066213,1.497599e+10,25.288389
26,2013-01-01,108.56,2013,7.416056e+10,4.970,48.415833,5.843416,2.415717,1.223174e+10,26.260012
27,2014-01-01,98.97,2014,7.523979e+10,4.910,43.273557,2.797585,1.373442,1.020880e+10,26.209669
28,2015-01-01,52.32,2015,5.307624e+10,4.960,37.794777,1.049546,4.027686,-2.224950e+08,34.806730
29,2016-01-01,43.64,2016,3.786700e+10,5.000,46.427649,-3.063598,12.443375,-1.363404e+09,43.649669
30,2017-01-01,54.12,2017,4.086663e+10,5.000,48.547865,0.153615,12.935918,1.684559e+09,41.854451
31,2018-01-01,71.34,2018,4.711247e+10,4.900,54.092294,1.500402,2.268547,5.974981e+09,37.580283
32,2019-01-01,64.30,2019,4.817424e+10,5.000,49.050628,2.479809,2.610572,4.193353e+09,36.767518
33,2020-01-01,41.96,2020,4.269300e+10,7.240,35.623556,-4.198961,2.759809,-3.163015e+08,36.394312
34,2021-01-01,70.86,2021,5.482541e+10,6.040,46.488747,5.616440,6.650299,8.202978e+09,29.798119
35,2022-01-01,100.93,2022,7.880747e+10,5.650,59.986848,4.714680,13.852259,2.347808e+10,26.995425
36,2023-01-01,82.49,2023,7.242847e+10,5.640,48.996414,1.354477,8.785430,8.329368e+09,34.539473
37,2024-01-01,80.52,2024,7.431588e+10,5.648,45.902546,4.071402,2.212172,4.671108e+09,36.787323
38,2025-01-01,69.14,2025,NaN,5.457,NaN,NaN,NaN,NaN,NaN